fixing some things from shellcheck and adding the ability to ignore cache when running the docker build script for updating tailscale versions

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,14 +1,17 @@
 #!/bin/bash
 
-#if [[ ! -v "TAILSCALE_AUTHKEY" ]]; then
-  #echo "error: must set TAILSCALE_AUTHKEY variable in order to move forward"
-  #exit 1
-#fi
+if [[ -z "$TAILSCALE_AUTHKEY" ]]; then
+  echo "error: must set TAILSCALE_AUTHKEY variable in order to move forward"
+  exit 1
+fi
 
 BUILD_DIR=$1
-CACHE_DIR=$2
+#CACHE_DIR=$2
 BUILDPACK_DIR="$(dirname "$(dirname "$0")")"
 
-mkdir -p $BUILD_DIR/bin
-tar -xzvf "$BUILDPACK_DIR/$STACK.tgz" -C "$BUILD_DIR/bin"
-mkdir -p $BUILD_DIR/var/run/tailscale $BUILD_DIR/var/cache/tailscale $BUILD_DIR/var/lib/tailscale
+# load stack-appropriate versions of the tailscale binaries into /app/bin
+mkdir -p "$BUILD_DIR"/bin
+tar -xzvf "$BUILDPACK_DIR/$STACK.tgz" -C "$BUILD_DIR"/bin
+
+# Copy the tailscale start script to the .profile.d directory
+cp "$BUILDPACK_DIR"/bin/start_tailscale.sh "$BUILD_DIR"/.profile.d/tailscale.sh
