removing the authkey env variable check

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-if [[ ! -v "TAILSCALE_AUTHKEY" ]]; then
-  echo "error: must set TAILSCALE_AUTHKEY variable in order to move forward"
-  exit 1
-fi
+#if [[ ! -v "TAILSCALE_AUTHKEY" ]]; then
+  #echo "error: must set TAILSCALE_AUTHKEY variable in order to move forward"
+  #exit 1
+#fi
 
 BUILD_DIR=$1
 CACHE_DIR=$2
